"""baskets

Revision ID: 3f8ad2283ded
Revises: 4acd099108bf
Create Date: 2026-07-11 12:19:25.003873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8ad2283ded'
down_revision: Union[str, Sequence[str], None] = '4acd099108bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baskets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('horizon', sa.Text(), nullable=True),
    sa.Column('invalidation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('basket_allocations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('basket_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('cost_basis_usd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('basket_id', 'instrument_id')
    )
    op.create_table('basket_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('basket_id', sa.BigInteger(), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('value_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('basket_id', 'taken_on')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket_snapshots')
    op.drop_table('basket_allocations')
    op.drop_table('baskets')
    # ### end Alembic commands ###
