"""rh sync columns

Revision ID: 4acd099108bf
Revises: acf93a59427d
Create Date: 2026-07-10 20:19:03.830515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4acd099108bf'
down_revision: Union[str, Sequence[str], None] = 'acf93a59427d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_accounts', sa.Column('cash_usd', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    op.add_column('broker_accounts', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('positions', sa.Column('last_price_usd', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('positions', sa.Column('prev_close_usd', sa.Numeric(precision=18, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'prev_close_usd')
    op.drop_column('positions', 'last_price_usd')
    op.drop_column('broker_accounts', 'last_synced_at')
    op.drop_column('broker_accounts', 'cash_usd')
    # ### end Alembic commands ###
