"""schema v1

Revision ID: acf93a59427d
Revises: 
Create Date: 2026-07-10 17:37:01.790384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acf93a59427d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broker_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('broker', sa.Enum('ibkr', 'robinhood', name='broker'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker', 'external_id')
    )
    op.create_table('instruments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('sec_type', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=True),
    sa.Column('con_id', sa.BigInteger(), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('strike', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('right', sa.String(length=1), nullable=True),
    sa.Column('multiplier', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('con_id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('total_value_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('per_account', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taken_on')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('owner', 'viewer', name='role'), nullable=False),
    sa.Column('mask_amounts', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cash_flows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('broker_account_id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.Enum('deposit', 'withdrawal', 'acats_in', 'acats_out', name='flow_kind'), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_local', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source_ref', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_ref')
    )
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('broker_account_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('avg_cost_usd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_account_id', 'instrument_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    op.drop_table('cash_flows')
    op.drop_table('users')
    op.drop_table('snapshots')
    op.drop_table('instruments')
    op.drop_table('broker_accounts')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
